baseurl = "/"
languageCode = "en-us"
#languageLang = "en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
title = "Mitesh Patel MD, MBA - Personal website"

[params]
description = "Mitesh Patel, MD, MBA is a Physician Executive and Behavioral Scientist.  He is Vice President for Clinical Transformation and National Lead for Behavioral Insights at Ascension Health. His research interests include nudges, digital health, wearables and gamification."
author="Mohan Balachandran"
robots="index, follow"

# RSS, categories and tags disabled for an easy start
# See configuration options for more details: 
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]
disable404 =  false
#googleAnalytics = "UA-147550714-1"
