backend:
  name: github
  repo: mohan2020/mpatel # Path to your Github repository
  branch: master # Branch to update
publish_mode: editorial_workflow
media_folder: "site/static/img/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/img/uploads" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Personal blog" # Used in the UI
    folder: "site/content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g. title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"} #title of the blog post
      - {label: "Publish Date", name: "date", widget: "date", format: "YYYY-MM-DD"} # date of publication / creation
      - {label: "Summary", name: "summary", widget: "string"} # summary of the post
      - {label: "Spotlight?", name: "spotlight", widget: "boolean", default: true}
      - {label: "Splash image", name: "image", widget: "image"} # background image. Use a large one. Check out unsplash.com for options
      - {label: "Body", name: "body", widget: "markdown"} #body of the case study
  - name: "press" # Used in routes, e.g., /admin/collections/blog
    label: "Press" # Used in the UI
    folder: "site/content/press" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{articlename}}" # Filename template, e.g. title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "articlename", widget: "string"} #title of the blog post
      - {label: "Publication Name", name: "journal", widget: "string"} #Abbreviated Journal name in citation
      - {label: "Publish Date", name: "date", widget: "date", format: "YYYY-MM-DD"} # date of publication / creation
      - {label: "Source", name: "source", widget: "string"} #Author Name
      - {label: "Spotlight?", name: "spotlight", widget: "boolean", default: true}
      - {label: "Summary", name: "summary", widget: "markdown", required: false} # summary of the post. Not used currently.
      - {label: "Thumbnail image", name: "image", widget: "image", required: false} # background image
  - name: "av" # Used in routes, e.g., /admin/collections/blog
    label: "Media: Audio, video" # Used in the UI
    folder: "site/content/av" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{articlename}}" # Filename template, e.g. title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "articlename", widget: "string"} #title of the blog post
      - {label: "Publication Name", name: "journal", widget: "string"} #Abbreviated Journal name in citation
      - {label: "Publish Date", name: "date", widget: "date", format: "YYYY-MM-DD"} # date of publication / creation
      - {label: "Source", name: "source", widget: "string"} #Author Name      
      - {label: "Spotlight?", name: "spotlight", widget: "boolean", default: true}
      - {label: "Summary", name: "summary", widget: "markdown", required: false} # summary of the post
      - {label: "Thumbnail image", name: "image", widget: "image", required: false} # background image
  - name: "opinions" # Used in routes, e.g., /admin/collections/blog
    label: "Opinion pieces" # Used in the UI
    folder: "site/content/opinions" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{articlename}}" # Filename template, e.g. title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "articlename", widget: "string"} #title of the blog post
      - {label: "Publication Name", name: "journal", widget: "string"} #Abbreviated Journal name in citation
      - {label: "Publish Date", name: "date", widget: "date", format: "YYYY-MM-DD"} # date of publication / creation
      - {label: "Source", name: "source", widget: "string"} #Author Name
      - {label: "Spotlight?", name: "spotlight", widget: "boolean", default: false}
      - {label: "Summary", name: "summary", widget: "markdown", required: false} # summary of the post
      - {label: "Thumbnail image", name: "image", widget: "image"} # background image
  - name: "publications" # Used in routes, e.g., /admin/collections/blog
    label: "Publications" # Used in the UI
    folder: "site/content/publications" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g. title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Study Name", name: "title", widget: "string"} #title of the blog post
      - {label: "Article Name", name: "articlename", widget: "string"} #title of the blog post
      - {label: "Topic", name: "topic", widget: "select", options: ["Nudges", "Wearables"]}
      - {label: "Publish Date", name: "date", widget: "date", format: "YYYY-MM-DD"} # date of publication / creation
      - {label: "Authors", name: "authors", widget: "string"} # publication authors
      - {label: "Source", name: "source", widget: "string"} #Author Name
      - {label: "Journal Abbr", name: "journal", widget: "string"} #Abbreviated Journal name in citation
      - {label: "Summary (not used currently)", name: "summary", widget: "string"} # summary of the post      
      - {label: "Thumbnail image (not used currently)", name: "image", widget: "image", required: false} # background image
      - {label: "Spotlight?", name: "spotlight", widget: "boolean", default: true}
